name: 'build-test'
on: # rebuild any PRs and main branch changes
  workflow_dispatch:

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: My Awesome
        uses: actions-on-packages/my-awesome@1.0.5
        
      - name: demo-aop-action
        uses: actions-on-packages/demo-aop-action@1.0.6
        with: 
          milliseconds: 1000

